cat_name_1 = input('Enter the name of cat 1: ')
cat_name_2 = input('Enter the name of cat 2: ')
cat_name_3 = input('Enter the name of cat 3: ')
cat_name_4 = input('Enter the name of cat 4: ')
cat_name_5 = input('Enter the name of cat 5: ')
cat_name_6 = input('Enter the name of cat 6: ')
print('The cat names are:')
print(f'{cat_name_1} {cat_name_2} {cat_name_3} {cat_name_4} {cat_name_5} {cat_name_6}')